### ISSUE TITLE
Consider removing global CSS rules which alter elements outside of Pathfinder 2 system UI.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/pf2e#1584]
Currently the system sets several global CSS rules which apply to all elements Foundry-wide. The most prominent of these is a global font-family change, depicted below with PF2E on the left and core Foundry on the right.

![image](http://gitlab.com/hooking/foundry-vtt---pathfinder-2e/uploads/a2b7df67809fcd7b69f940e21bdbd0fb/image.png)

## Examples
Some example rules of this type include:
```css
body {
    font-family: $sans-serif;
    color: var(--body);
}
h1,
h2,
h3,
h4 {
    font-weight: 600;
}
p {
    font-weight: 500;
}
a[href] {
    color: var(--primary);
}
```

I am interested whether the team would consider removing these rules in favor of ones which limit scope to only define styles for UI elements which are specifically added by the PF2E system. I can make a couple of logical arguments in favor of this:

### 1. Separation of concerns
It certainly makes sense for game systems to provide styling rules for UI elements which pertain to the system, but I would argue that the styling of other UI elements (either core or those added by modules) should be left to either the provider of that UI element OR to a specialized UI overhaul module which specifically strives to rework the UI in a holistic way.

### 2. Possibility of layout conflicts
The current scope of PF2E system rules means that certain UI elements developed with the core UI styles in mind (either by core or by another module) can experience some unexpected rendering outcomes when exposed to the PF2E system.

## Recommendation
The recommended best practice (or so I claim) would be to namespace CSS rules in a way that can be targeted specifically to elements that the system "controls" (sheets, compendium browser, journal entries, etc...). In other words, instead of:
```css
body {
    font-family: $sans-serif;
    color: var(--body);
}
```
Prefer a `.pf2e` class namespace where the `pf2e` class is added to sheets or other interface elements where system-specific styles should be applied.
```css
.pf2e {
    font-family: $sans-serif;
    color: var(--body);
}
```
Let me know if this makes sense and if you would consider accepting a change. If so I could try and put together a MR.
